version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true
  
  test:
    cmds:
      - dart test

  build:
    cmds:
      - powershell -c mkdir -Force dist>nul
      - dart compile exe ./bin/apiary_dart.dart -o ./dist/apiary_dart.exe
    deps:
      - test
